/**:
  ros__parameters:
    # -- Node Configurations --
    planning_algorithm: "astar"  # "astar" or "rrtstar"
    waypoints_velocity: 8.0
    update_rate: 10.0
    th_arrived_distance_m: 0.01
    th_stopped_time_sec: 1.0
    th_stopped_velocity_mps: 0.01
    th_course_out_distance_m: 0.2
    vehicle_shape_margin_m: 0.8
    replan_when_obstacle_found: true
    replan_when_course_out: false

    # -- Configurations common to the all planners --
    # base configs
    time_limit: 30000.0
    # robot configs # TODO replace by vehicle_info
    robot_length: 0.548
    robot_width: 0.270292
    robot_base2back: 0.11
    minimum_turning_radius: 1.0
    maximum_turning_radius: 30.0

    turning_radius_size: 1
    # search configs
    theta_size: 72
    angle_goal_range: 6.0
    curve_weight: 5.0
    reverse_weight: 100.0
    lateral_goal_range: 0.1
    longitudinal_goal_range: 0.1
    # costmap configs
    obstacle_threshold: 100

    # -- A* search Configurations --
    astar:
      only_behind_solutions: false
      use_back: false
      distance_heuristic_weight: 0.1

    # -- RRT* search Configurations --
    rrtstar:
      enable_update: true
      use_informed_sampling: true
      max_planning_time: 150.0
      neighbor_radius: 8.0
      margin: 0.1
